/* Generated by myoptions.h generator - v0.9.0 */
/* https://trip5.github.io/ehRadio_myoptions/generator.html */

/* esp32-S3-devkit-C1 44 pins https://randomnerdtutorials.com/esp32-s3-devkitc-pinout-guide */

/* HSPI (SPI 2) GPIO 11 - MOSI, GPIO 12 - CLK, GPIO 13 - MISO, GPIO 10 - CS */

#pragma once

#ifndef ARDUINO_ESP32S3_DEV
    #define ARDUINO_ESP32S3_DEV
#endif

#define LANGUAGE HU // HU Enter your own language here!!
#define NAMEDAYS_FILE HU // HU
/*****************************************/

#define DSP_MODEL DSP_ILI9488
/*****************************************/

/* Kijelzo vezerlo
   0 = ILI9488
   1 = ST7796

   A sajat radio alapja ILI9488 + XPT2046, ezert az alapertelmezett ertek 0.
   ST7796 buildhez allitsd 1-re. */
#ifndef DISPLAY_PROFILE_ST7796
#define DISPLAY_PROFILE_ST7796 0
#endif
/*****************************************/

#define TFT_DC    10
#define TFT_CS    18
#define TFT_RST   -1
#define TFT_SCK   12
#define TFT_MOSI  11
//#define TFT_MISO  13

#define BRIGHTNESS_PIN 14
/*****************************************/

/* Touch panel */
#ifndef TS_MODEL_XPT2046
#define TS_MODEL_XPT2046 1
#endif
#ifndef TS_MODEL_GT911
#define TS_MODEL_GT911 2
#endif
#ifndef TS_MODEL_FT6X36
#define TS_MODEL_FT6X36 3
#endif

/* Touch panel
   Alapértelmezés: a saját rádió rezisztív XPT2046 panelje.
   Ha a kapacitív ILI9488 kell, csak a
   TOUCH_PROFILE_FT6X36 értékét állítsd 1-re. */
   // 0 = saját rádió / rezisztív XPT2046
// 1 = kapacitív ILI9488 / FT6X36 teszt-build
#ifndef TOUCH_PROFILE_FT6X36
#define TOUCH_PROFILE_FT6X36 0
#endif

#if TOUCH_PROFILE_FT6X36
  #include "options_touch_ft6x36.h"
#else
  #include "options_touch_xpt2046.h"
#endif
/*****************************************/
/* SD CARD */
#define SDC_CS    39
#define SD_SPIPINS 12, 13, 11, SDC_CS  // SCK, MISO, MOSI, CS
#define SDSPISPEED     4000000 /* 4MHz - Slower speed to prevent display flicker on shared SPI bus */
/****************************************/
/*  I2S DAC  */

/* CS4344 / PCM5102A DAC */
#define I2S_DOUT 38
#define I2S_BCLK 21
#define I2S_LRC  47
//#define I2S_MCLK 17

/* Album cover lookup */
#define USE_LASTFM_COVER
#define LASTFM_API_KEY "API Key"    // https://www.last.fm/api/authentication Szerezz be ingyenes API-key-t és add meg itt / Get an Last.fm API Key

/* ENCODER 1 */
#define ENC_BTNR 6 // S2
#define ENC_BTNL 4 // S1
#define ENC_BTNB 5 // KEY
//#define ENC_INTERNALPULLUP		true

/* ENCODER 2 */
//#define ENC2_BTNR 16 // S2
//#define ENC2_BTNL 7 // S1
//#define ENC2_BTNB 15 // KEY
//#define ENC2_INTERNALPULLUP		true



